Allow handling lines longer than 64 KiB
Without this, nix-fast-build can crash with the following error:

    File "...python3-3.13.11/lib/python3.13/asyncio/streams.py", line 571, in readline
        raise ValueError(e.args[0])
    ValueError: Separator is found, but chunk is longer than limit

Note that this error is caused by "async for line in proc.stdout:"
line added in the previous commit.